# Generated by Django 5.1.4 on 2026-07-04 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='scenario_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budgets.budgetscenario')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['scenario', 'department'], name='budgets_bud_scenari_f80b82_idx'), models.Index(fields=['scenario', 'category'], name='budgets_bud_scenari_ba7c5a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('budget_amount__gte', 0), ('actual_amount__gte', 0)), name='lineitem_amounts_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='AssistantRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_runs', to='budgets.budgetscenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scenario', 'status'], name='budgets_ass_scenari_d181cb_idx')],
            },
        ),
    ]
